### ISSUE TITLE
make时出现问题

### ISSUE THREAD

**Issue by zjh-de-github** [Coekjan/Jrinx#1]
LDSPP     kern.ld
 CC        kern/tests/asid-test.o
 CC        kern/tests/serial-test.o
 CC        kern/tests/pmm-test.o
 CC        kern/tests/vmm-test.o
 CC        kern/drivers/cpus.o
 CC        kern/drivers/devicetree.o
 CC        kern/drivers/aliases.o
 CC        kern/drivers/chosen.o
 CC        kern/drivers/serialport.o
 CC        kern/drivers/rtc/goldfish.o
 CC        kern/drivers/intc.o
 CC        kern/drivers/mems.o
 CC        kern/drivers/serial/sifiveuart0.o
 CC        kern/drivers/serial/uart16550a.o
 CC        kern/drivers/realtime.o
 CC        kern/drivers/irq/plic.o
 CC        kern/drivers/device.o
 CC        kern/mm/pmm.o
 CC        kern/mm/asid.o
 CC        kern/mm/vmm.o
 CC        kern/mm/kalloc.o
 CC        kern/chan/queuing.o
 CC        kern/chan/channel.o
 CC        kern/lib/logger.o
 CC        kern/lib/bootargs.o
 CC        kern/lib/errors.o
 CC        kern/lib/sbi.o
 CC        kern/lib/boottime.o
 CC        kern/boot/init.o
 CC        kern/traps/traps.o
 CC        kern/traps/interrupt.o
 CC        kern/traps/timer.o
 CC        kern/traps/syscalls.o
 CC        kern/traps/pagefault.o
 CC        kern/lock/lock.o
 CC        kern/lock/spinlock.o
 CC        kern/comm/buffer.o
 CC        kern/comm/blackboard.o
 CC        kern/multitask/process.o
 CC        kern/multitask/sched.o
 CC        kern/multitask/partition.o
 AS        kern/boot/start.o
/home/zjh/Jrinx/kern/multitask/partition.c: Assembler messages:
/home/zjh/Jrinx/kern/multitask/partition.c:276: Error: unrecognized opcode `fence.i', extension `zifencei' required
Makefile:213: recipe for target 'target/kern/multitask/partition.o' failed
make: *** [target/kern/multitask/partition.o] Error 1
make: *** Waiting for unfinished jobs....

使用riscv64-unknown-linux-gnu-gcc编译时出现了这个问题，原因是选项没有添加zifencei，于是我在makefile中添加选项：
CFLAGS			+= -march=rv64izifencei
又出现了以下问题

 LDSPP     kern.ld
 CC        kern/tests/asid-test.o
cc1: error: requested ABI requires '-march' to subsume the 'D' extension
Makefile:214: recipe for target 'target/kern/tests/asid-test.o' failed
make: *** [target/kern/tests/asid-test.o] Error 1

请问是我配置的不对嘛，求指教

**Comment by Coekjan** [comment]
您 GCC 工具链的版本是？

**Comment by zjh-de-github** [comment]
> 您 GCC 工具链的版本是？
COLLECT_LTO_WRAPPER=/opt/riscv/libexec/gcc/riscv64-unknown-linux-gnu/12.2.0/lto-wrapper
应该是12.2.0

**Comment by Coekjan** [comment]
尝试在命令行中通过：

```console
$ riscv64-unknown-linux-gnu-gcc --version
```

检查一下版本？

**Comment by zjh-de-github** [comment]
> 

对的 我是这样查看的版本 
`riscv64-unknown-linux-gnu-gcc (g2ee5e430018) 12.2.0`

**Comment by Coekjan** [comment]
暂时不太能猜测出来您面临的问题，但您可以尝试在 docker 容器里构建，那样应该会比较顺利。

**Comment by Coekjan** [comment]
暂时不太能猜测出来您面临的问题，但您可以尝试在 docker 容器里构建，那样应该会比较顺利。

具体而言，可以通过：

```console
$ docker pull coekjan/jrinx-devel:latest
```

来拉取 docker 镜像，然后通过：

```console
$ docker run -v /path/to/your/repo:/workdir -w /workdir --rm -it coekjan/jrinx-devel:latest /bin/bash
```

进入容器，然后在容器中配置环境变量：

```console
$ export CROSS_COMPILE=riscv64-linux-gnu-
```

再进行构建。若构建中提示 Git 仓库不安全，可参照提示来配置安全仓库。

**Comment by ostarJoy** [comment]
使用 `march=riscv64g` 可以完成编译，gcc版本为12.3 `g` 扩展相比起 `imafd` 扩展增加了对`fence`以及`csr`的相关扩展，请问这样修改会改变项目的行为吗？

**Comment by ostarJoy** [comment]
> 使用 `march=riscv64g` 可以完成编译，gcc版本为12.3 `g` 扩展相比起 `imafd` 扩展增加了对`fence`以及`csr`的相关扩展，请问这样修改会改变项目的行为吗？

我使用你提供的docker镜像中发现你使用的是11.3版本的riscv64-gcc, 在gcc-12 版本中，fence以及csr扩展默认不开启，这导致了使用gcc-12编译会出现问题。

https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/aE1ZeHHCYf4

**Comment by Coekjan** [comment]
> > 使用 `march=riscv64g` 可以完成编译，gcc版本为12.3 `g` 扩展相比起 `imafd` 扩展增加了对`fence`以及`csr`的相关扩展，请问这样修改会改变项目的行为吗？
> 
> 我使用你提供的docker镜像中发现你使用的是11.3版本的riscv64-gcc, 在gcc-12 版本中，fence以及csr扩展默认不开启，这导致了使用gcc-12编译会出现问题。
> 
> https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/aE1ZeHHCYf4

docker 里是 ubuntu 22.04 LTS 软件源中的版本，我自己用的是 https://aur.archlinux.org/packages/riscv-gnu-toolchain-bin ，都是能跑的。在 https://aur.archlinux.org/packages/riscv-gnu-toolchain-bin 中，gcc 版本是 12.2.0（g2ee5e430018），应该与楼上是一样的版本。

**Comment by Coekjan** [comment]
> 使用 `march=riscv64g` 可以完成编译，gcc版本为12.3 `g` 扩展相比起 `imafd` 扩展增加了对`fence`以及`csr`的相关扩展，请问这样修改会改变项目的行为吗？

应该不会，不放心的话可以尝试 `./scripts/run-tests -pr` 跑一遍回归测试。

**Comment by ostarJoy** [comment]
我是使用`pacman`的`riscv64-gcc`会出问题，使用aur的没有问题话应该是两者在构建bin的时候存在差别，我猜测。

https://stackoverflow.com/questions/63146418/differentiating-between-rv64imafd-and-rv64imafdc-isa

**Comment by Coekjan** [comment]
> 我是使用`pacman`的`riscv64-gcc`会出问题，使用aur的没有问题话应该是两者在构建bin的时候存在差别，我猜测。
> 
> https://stackoverflow.com/questions/63146418/differentiating-between-rv64imafd-and-rv64imafdc-isa

使用 pacman 源里 riscv64-gcc 时，应该对 `CFLAGS` 做什么修订？我可以修改一下 Makefile，使其更“兼容”一些。

**Comment by ostarJoy** [comment]
> > 我是使用`pacman`的`riscv64-gcc`会出问题，使用aur的没有问题话应该是两者在构建bin的时候存在差别，我猜测。
> > https://stackoverflow.com/questions/63146418/differentiating-between-rv64imafd-and-rv64imafdc-isa
> 
> 使用 pacman 源里 riscv64-gcc 时，应该对 `CFLAGS` 做什么修订？我可以修改一下 Makefile，使其更“兼容”一些。

将`march=rv64imafd`变成`march=rv64imafd_zifencei` 可以通过编译，即增加fencei的指令集扩展

**Comment by Coekjan** [comment]
已修缮 Makefile，请拉取一下最新的 master，再尝试一下
