### ISSUE TITLE
docker编译后无法run

### ISSUE THREAD

**Issue by preychiken** [Coekjan/Jrinx#3]
root@0326fa107002:/workdir# ls
Dockerfile  jrinx.logo  lib       README.md  target
docs        kern        Makefile  scripts    tests-conf
include     kern.ldS    opensbi   sys-conf   user
root@0326fa107002:/workdir# make run
make[1]: *** 没有规则可制作目标“all”。 停止。
make: *** [Makefile:279：opensbi] 错误 2
root@0326fa107002:/workdir#

**Comment by preychiken** [comment]
![image](https://github.com/Jrinx/Jrinx/assets/59829229/1ae07005-c89c-40d8-86ef-78d9aac1ab4b)

**Comment by Coekjan** [comment]
是否已拉取子模块 opensbi？

**Comment by preychiken** [comment]
![image](https://github.com/Jrinx/Jrinx/assets/59829229/f1e76e09-6325-4baf-8096-e0ffd0e29ab6)
这是成功跑起了吗，不需要用qemu嘛

**Comment by Coekjan** [comment]
> ![image](https://private-user-images.githubusercontent.com/59829229/297309097-f1e76e09-6325-4baf-8096-e0ffd0e29ab6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0Nzk2ODYsIm5iZiI6MTcwNTQ3OTM4NiwicGF0aCI6Ii81OTgyOTIyOS8yOTczMDkwOTctZjFlNzZlMDktNjMyNS00YmFmLTgwOTYtZTBmZmQwZTI5YWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA4MTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZWYyZDNkNzZmYjBhZWRkOTFjNzBmNDUyZTY4MDM5OTgyN2FkNWY5YjA0ZWZhNDJlNDc5NjMyNWEwMzExYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GibTE3mfKh2_g2C3BxYEoPEPr2CYY3ahAAsJt5JEUbk) 这是成功跑起了吗，不需要用qemu嘛

这是已经成功运行了，docker 里有 qemu，所以不需要手动安装

**Comment by preychiken** [comment]
ok，谢谢大佬

**Comment by preychiken** [comment]
![image](https://github.com/Jrinx/Jrinx/assets/59829229/c5a912ed-30b1-4631-be78-98c73a4cf996)
启动后发现这个异常是什么原因

**Comment by Coekjan** [comment]
> ![image](https://private-user-images.githubusercontent.com/59829229/298825395-c5a912ed-30b1-4631-be78-98c73a4cf996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTEzODksIm5iZiI6MTcwNTk5MTA4OSwicGF0aCI6Ii81OTgyOTIyOS8yOTg4MjUzOTUtYzVhOTEyZWQtMzBiMS00NjMxLWJlNzgtOThjNzNhNGNmOTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA2MjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMzUwZjgzMmMzYzljMGEwOWRiYzIxYmI5MjNmYzYyMTA2YmRkM2Y5YTczMDJiZWMwNGFkYTQwOTM0MDc0M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gatogMEn99Fe4SNHeDssI4hfSD7FkG2hZtVyEVo8A8Y) 启动后发现这个异常是什么原因

如果你没有指定系统配置，那应该正常现象，因为系统不知道要运行什么任务。你可以考虑指定系统配置来让系统运行特定的任务，参考：

https://github.com/Jrinx/Jrinx/blob/bfeed3f7ed0023d5c1d159b42c2bc862e1896fe7/README.md?plain=1#L40-L54

**Comment by preychiken** [comment]
噢噢 可以了
